# Generated by Django 2.0.6 on 2018-06-20 20:49

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the instance', max_length=50)),
                ('arguments', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='A dictionary of arguments, where the keys are the argument name and the values are their corresponding values', null=True)),
                ('author', models.ForeignKey(help_text='The author of this instance', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TaskScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the task', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='A description of the task', null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('required_arguments', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='A list of required argument names', null=True)),
                ('default_arguments', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='A dictionary of default arguments, where the keys are the argument name and the values are their corresponding default values', null=True)),
                ('script_path', models.CharField(help_text='The path of the script to run, relative to the task_scripts directory', max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='task_type',
            field=models.ForeignKey(help_text=('The task type for which this is an instance',), null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.TaskType'),
        ),
    ]
