# Generated by Django 2.0.6 on 2018-06-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskinstance_datetime_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskinstance',
            name='name',
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='uuid',
            field=models.CharField(editable=False, help_text='The UUID for the running job', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='script_path',
            field=models.CharField(help_text='The path of the script to run, relative to the task_library directory', max_length=400),
        ),
    ]
