# Generated by Django 2.0.6 on 2018-06-24 21:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20180624_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktype',
            name='required_arguments',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='A JSON array of required argument names'),
        ),
    ]
