# Generated by Django 2.0.6 on 2018-06-24 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='queue',
            field=models.ForeignKey(blank=True, help_text='The queue this instance runs on. If left blank, then the default queue is used.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.TaskQueue'),
        ),
        migrations.AddField(
            model_name='taskqueue',
            name='active',
            field=models.BooleanField(default=True, help_text='A boolean showing the status of the queue. As of now, this needs to be toggled manually.'),
        ),
        migrations.AddField(
            model_name='taskqueue',
            name='description',
            field=models.TextField(blank=True, help_text='A description of the queue', null=True),
        ),
        migrations.AddField(
            model_name='taskqueue',
            name='name',
            field=models.CharField(default=2, help_text='The name of the Celery queue', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='task_type',
            field=models.ForeignKey(help_text='The task type for which this is an instance', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.TaskType'),
        ),
    ]
