# Generated by Django 2.0.6 on 2018-06-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20180624_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='state',
            field=models.CharField(choices=[('CREATED', 'created'), ('PUBLISH', 'published'), ('RUNNING', 'running'), ('SUCCESS', 'successful'), ('FAIL', 'failed'), ('REVOKED', 'revoked')], default='CREATED', max_length=7),
        ),
    ]
