# Generated by Django 2.0.6 on 2018-06-25 22:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20180625_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskinstance',
            name='id',
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The UUID for the running job', primary_key=True, serialize=False, verbose_name='UUID'),
        ),
    ]
