# Generated by Django 2.0.6 on 2018-06-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20180625_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='datetime_finished',
            field=models.DateTimeField(editable=False, help_text='When the job finished.', null=True),
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, help_text='When the job was created'),
        ),
    ]
