# Generated by Django 2.0.6 on 2018-06-26 21:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20180626_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskqueue',
            name='name',
            field=models.CharField(help_text='The name of the Celery queue', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message=' @/+/-/_ only', regex='^[\\w@+-]+$')]),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='name',
            field=models.CharField(help_text='The name of the task', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message=' @/+/-/_ only', regex='^[\\w@+-]+$')]),
        ),
    ]
