# Generated by Django 2.0.6 on 2018-06-29 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_auto_20180626_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskinstance',
            options={'ordering': ['-datetime_created']},
        ),
        migrations.AlterModelOptions(
            name='taskqueue',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tasktype',
            options={'ordering': ['name']},
        ),
    ]
