# Generated by Django 2.0.6 on 2018-06-30 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_auto_20180629_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskinstance',
            old_name='queue',
            new_name='task_queue',
        ),
        migrations.RenameField(
            model_name='taskinstance',
            old_name='author',
            new_name='user',
        ),
    ]
