# Generated by Django 2.0.6 on 2018-06-30 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_auto_20180630_0147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskqueue',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tasktype',
            options={},
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='task_queue',
            field=models.ForeignKey(blank=True, help_text='The queue this instance runs on. If left blank, then the default queue is used.', null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.TaskQueue'),
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='task_type',
            field=models.ForeignKey(default=1, help_text='The task type for which this is an instance', on_delete=django.db.models.deletion.PROTECT, to='tasks.TaskType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='user',
            field=models.ForeignKey(default=1, help_text='The author of this instance', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
