# Generated by Django 2.0.6 on 2018-06-30 22:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0018_auto_20180630_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='user',
            field=models.ForeignKey(default=1, help_text='The author of this task', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='name',
            field=models.CharField(help_text='The name of the task', max_length=50, validators=[django.core.validators.RegexValidator(message=' @/+/-/_ only', regex='^[\\w@+-]+$')]),
        ),
        migrations.AlterUniqueTogether(
            name='tasktype',
            unique_together={('name', 'user')},
        ),
    ]
