# Generated by Django 2.0.6 on 2018-07-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_auto_20180702_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinstance',
            name='state',
            field=models.CharField(choices=[('CREATED', 'created'), ('PUBLISHED', 'published'), ('RUNNING', 'running'), ('SUCCESSFUL', 'successful'), ('FAILED', 'failed'), ('TERMINATED', 'terminated')], default='CREATED', max_length=10),
        ),
    ]
