# Generated by Django 2.0.6 on 2018-07-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_auto_20180704_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='container_image',
            field=models.CharField(default='ubuntu:14.04', help_text='The container name and tag, e.g., "ubuntu:14.04"', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasktype',
            name='container_type',
            field=models.CharField(choices=[('DOCKER', 'Docker'), ('SINGULARITY', 'Singularity')], default='DOCKER', help_text='The type of the container provided', max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='script_path',
            field=models.CharField(help_text='The path of the script to run, inside of the container image. *Must* be executable!', max_length=400),
        ),
    ]
