# Generated by Django 2.0.6 on 2018-07-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_auto_20180705_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktype',
            name='container_image',
            field=models.CharField(help_text='The container name and tag. E.g., "ubuntu:14.04" for Docker; "docker://ubuntu:14.04" or "shub://vsoch/hello-world" for Singularity.', max_length=200),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='container_type',
            field=models.CharField(choices=[('DOCKER', 'Docker'), ('SINGULARITY', 'Singularity')], help_text='The type of container provided', max_length=11),
        ),
    ]
