# Generated by Django 2.0.6 on 2018-07-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_auto_20180705_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='logs_path',
            field=models.CharField(blank=True, default='/logs/', help_text='The path of the logs directory inside of the container. Specify null if no logs directory.', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='script_path',
            field=models.CharField(help_text='The path of the script to run inside of the container. *Must* be executable!', max_length=400),
        ),
    ]
