# Generated by Django 2.0.6 on 2018-07-07 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_delete_taskscheduler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasktype',
            old_name='default_arguments',
            new_name='required_arguments_default_values',
        ),
    ]
