# Generated by Django 2.0.6 on 2018-07-07 23:45

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The UUID for the running job', primary_key=True, serialize=False, verbose_name='UUID')),
                ('state', models.CharField(choices=[('CREATED', 'created'), ('PUBLISHED', 'published'), ('RUNNING', 'running'), ('SUCCESSFUL', 'successful'), ('FAILED', 'failed'), ('TERMINATED', 'terminated')], default='CREATED', max_length=10)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, help_text='When the job was created')),
                ('datetime_finished', models.DateTimeField(editable=False, help_text='When the job finished.', null=True)),
                ('arguments', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='A JSON dictionary of arguments, where the keys are the argument name and the values are their corresponding values')),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
        migrations.CreateModel(
            name='TaskQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the Celery queue', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message=' @/+/-/_ only', regex='^[\\w@+-]+$')])),
                ('description', models.TextField(blank=True, help_text='A description of the queue')),
                ('active', models.BooleanField(default=True, help_text='A boolean showing the status of the queue. As of now, this needs to be toggled manually.')),
            ],
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the task', max_length=200, validators=[django.core.validators.RegexValidator(message=' @/+/-/_ only', regex='^[\\w@+-]+$')])),
                ('description', models.TextField(blank=True, help_text='A description of the task')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('container_image', models.CharField(help_text='The container name and tag. E.g., "ubuntu:14.04" for Docker; "docker://ubuntu:14.04" or "shub://vsoch/hello-world" for Singularity.', max_length=200)),
                ('container_type', models.CharField(choices=[('DOCKER', 'Docker'), ('SINGULARITY', 'Singularity')], help_text='The type of container provided', max_length=11)),
                ('script_path', models.CharField(help_text='The path of the script to run inside of the container. *Must* be executable!', max_length=400)),
                ('logs_path', models.CharField(blank=True, default='/logs/', help_text='The path of the logs directory inside of the container. Specify null if no logs directory.', max_length=400, null=True)),
                ('required_arguments', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='A JSON array of required argument names')),
                ('required_arguments_default_values', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='A JSON dictionary of default values for required arguments, where the keys are the argument names and the values are their corresponding default values')),
                ('user', models.ForeignKey(help_text='The author of this task', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='task_queue',
            field=models.ForeignKey(help_text='The queue this instance runs on. If left blank, then the default queue is used.', on_delete=django.db.models.deletion.PROTECT, to='tasksapi.TaskQueue'),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='task_type',
            field=models.ForeignKey(help_text='The task type for which this is an instance', on_delete=django.db.models.deletion.PROTECT, to='tasksapi.TaskType'),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='user',
            field=models.ForeignKey(help_text='The author of this instance', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tasktype',
            unique_together={('name', 'user')},
        ),
    ]
