# Generated by Django 2.1.2 on 2018-12-05 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasksapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containertaskinstance',
            name='task_queue',
            field=models.ForeignKey(help_text='The queue this instance runs on.', on_delete=django.db.models.deletion.CASCADE, to='tasksapi.TaskQueue'),
        ),
        migrations.AlterField(
            model_name='containertaskinstance',
            name='task_type',
            field=models.ForeignKey(help_text='The task type for which this is an instance.', on_delete=django.db.models.deletion.CASCADE, to='tasksapi.ContainerTaskType'),
        ),
        migrations.AlterField(
            model_name='containertaskinstance',
            name='user',
            field=models.ForeignKey(help_text='The author of this instance.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='containertasktype',
            name='user',
            field=models.ForeignKey(help_text='The author of this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='executabletaskinstance',
            name='task_queue',
            field=models.ForeignKey(help_text='The queue this instance runs on.', on_delete=django.db.models.deletion.CASCADE, to='tasksapi.TaskQueue'),
        ),
        migrations.AlterField(
            model_name='executabletaskinstance',
            name='task_type',
            field=models.ForeignKey(help_text='The task type for which this is an instance.', on_delete=django.db.models.deletion.CASCADE, to='tasksapi.ExecutableTaskType'),
        ),
        migrations.AlterField(
            model_name='executabletaskinstance',
            name='user',
            field=models.ForeignKey(help_text='The author of this instance.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='executabletasktype',
            name='user',
            field=models.ForeignKey(help_text='The author of this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskqueue',
            name='user',
            field=models.ForeignKey(help_text='The creator of the queue.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
