# Generated by Django 2.1.2 on 2018-12-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksapi', '0002_auto_20181204_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containertasktype',
            name='command_to_run',
            field=models.CharField(help_text='The command to run to execute the task. For example, "python /app/myscript.py". Note that shell operators will *not* be parsed; for example, | and &&. Arguments will be appended to the end of the command.', max_length=400),
        ),
        migrations.AlterField(
            model_name='executabletasktype',
            name='command_to_run',
            field=models.CharField(help_text='The command to run to execute the task. For example, "python /app/myscript.py". Note that shell operators will *not* be parsed; for example, | and &&. Arguments will be appended to the end of the command.', max_length=400),
        ),
    ]
