# Generated by Django 2.1 on 2018-09-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksapi', '0002_auto_20180828_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containertasktype',
            name='name',
            field=models.CharField(help_text='The name of the task', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='executabletasktype',
            name='name',
            field=models.CharField(help_text='The name of the task', max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='containertasktype',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='executabletasktype',
            unique_together=set(),
        ),
    ]
