# Generated by Django 2.1.2 on 2018-10-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksapi', '0003_auto_20180919_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containertasktype',
            name='command_to_run',
            field=models.CharField(help_text='The command to run to execute the task. For example, "python /app/myscript.py". Note that shell operators will *not* be parsed; for example, | and &&. Arguments will be added to the end of this command.', max_length=400),
        ),
        migrations.AlterField(
            model_name='executabletasktype',
            name='command_to_run',
            field=models.CharField(help_text='The command to run to execute the task. For example, "python /app/myscript.py". Note that shell operators will *not* be parsed; for example, | and &&. Arguments will be added to the end of this command.', max_length=400),
        ),
    ]
