# Generated by Django 2.1.2 on 2018-12-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksapi', '0004_user_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskqueue',
            name='runs_docker_container_tasks',
            field=models.BooleanField(blank=True, default=True, help_text='A boolean specifying whether the queue runs container tasks that run in Docker containers. Defaults to True.', verbose_name='runs Docker container tasks'),
        ),
        migrations.AddField(
            model_name='taskqueue',
            name='runs_executable_tasks',
            field=models.BooleanField(blank=True, default=True, help_text='A boolean specifying whether the queue runs executable tasks. Defaults to True.'),
        ),
        migrations.AddField(
            model_name='taskqueue',
            name='runs_singularity_container_tasks',
            field=models.BooleanField(blank=True, default=True, help_text='A boolean specifying whether the queue runs container tasks that run in Singularity containers. Defaults to True.', verbose_name='runs Singularity container tasks'),
        ),
    ]
