# Generated by Django 2.0.6 on 2018-07-20 23:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksapi', '0004_auto_20180718_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='name',
            field=models.CharField(blank=True, help_text='An optional non-unique name for thetask instance', max_length=200, validators=[django.core.validators.RegexValidator(message=' @/+/-/_ only', regex='^[\\w@+-]+$')]),
        ),
    ]
