# Generated by Django 2.0.6 on 2018-07-21 20:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasksapi', '0005_taskinstance_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='directories_to_bind',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text="A JSON dictionary where the keys are directories on the worker's machine and the corresponding values are directories in the container to bind the keys to. Make sure the directories in the container are created and ready to bind."),
        ),
    ]
