# Generated by Django 2.1.2 on 2018-10-17 21:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasksapi', '0005_auto_20181009_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containertaskinstance',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, help_text='When the job was created.'),
        ),
        migrations.AlterField(
            model_name='containertaskinstance',
            name='name',
            field=models.CharField(blank=True, help_text='An optional non-unique name for the task instance.', max_length=200),
        ),
        migrations.AlterField(
            model_name='containertaskinstance',
            name='task_queue',
            field=models.ForeignKey(help_text='The queue this instance runs on.', on_delete=django.db.models.deletion.PROTECT, to='tasksapi.TaskQueue'),
        ),
        migrations.AlterField(
            model_name='containertaskinstance',
            name='task_type',
            field=models.ForeignKey(help_text='The task type for which this is an instance.', on_delete=django.db.models.deletion.PROTECT, to='tasksapi.ContainerTaskType'),
        ),
        migrations.AlterField(
            model_name='containertaskinstance',
            name='user',
            field=models.ForeignKey(help_text='The author of this instance.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='containertaskinstance',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The UUID for the running job.', primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='containertasktype',
            name='container_type',
            field=models.CharField(choices=[('docker', 'Docker'), ('singularity', 'Singularity')], help_text='The type of container provided.', max_length=11),
        ),
        migrations.AlterField(
            model_name='containertasktype',
            name='description',
            field=models.TextField(blank=True, help_text='A description of the task.'),
        ),
        migrations.AlterField(
            model_name='containertasktype',
            name='name',
            field=models.CharField(help_text='The name of the task.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='containertasktype',
            name='user',
            field=models.ForeignKey(help_text='The author of this task.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='executabletaskinstance',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, help_text='When the job was created.'),
        ),
        migrations.AlterField(
            model_name='executabletaskinstance',
            name='name',
            field=models.CharField(blank=True, help_text='An optional non-unique name for the task instance.', max_length=200),
        ),
        migrations.AlterField(
            model_name='executabletaskinstance',
            name='task_queue',
            field=models.ForeignKey(help_text='The queue this instance runs on.', on_delete=django.db.models.deletion.PROTECT, to='tasksapi.TaskQueue'),
        ),
        migrations.AlterField(
            model_name='executabletaskinstance',
            name='task_type',
            field=models.ForeignKey(help_text='The task type for which this is an instance.', on_delete=django.db.models.deletion.PROTECT, to='tasksapi.ExecutableTaskType'),
        ),
        migrations.AlterField(
            model_name='executabletaskinstance',
            name='user',
            field=models.ForeignKey(help_text='The author of this instance.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='executabletaskinstance',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The UUID for the running job.', primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='executabletasktype',
            name='description',
            field=models.TextField(blank=True, help_text='A description of the task.'),
        ),
        migrations.AlterField(
            model_name='executabletasktype',
            name='name',
            field=models.CharField(help_text='The name of the task.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='executabletasktype',
            name='user',
            field=models.ForeignKey(help_text='The author of this task.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskqueue',
            name='description',
            field=models.TextField(blank=True, help_text='A description of the queue.'),
        ),
        migrations.AlterField(
            model_name='taskqueue',
            name='name',
            field=models.CharField(help_text='The name of the Celery queue.', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message=' @/+/-/_ only', regex='^[\\w@+-]+$')]),
        ),
        migrations.AlterField(
            model_name='taskqueue',
            name='user',
            field=models.ForeignKey(help_text='The creator of the queue.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
