# Generated by Django 2.0.7 on 2018-07-22 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasksapi', '0006_tasktype_directories_to_bind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskqueue',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tasktype',
            options={'ordering': ['id']},
        ),
    ]
