# Generated by Django 2.0.7 on 2018-07-27 22:18

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasksapi', '0007_auto_20180722_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinstance',
            name='arguments',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text="A JSON dictionary of arguments, where the keys are the argument names and the values are their corresponding values. A task instance must specify values for all values of a task type's required arguments for which no default value exists. Defaults to {}."),
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='name',
            field=models.CharField(blank=True, help_text='An optional non-unique name for the task instance', max_length=200, validators=[django.core.validators.RegexValidator(message=' @/+/-/_ only', regex='^[\\w@+-]+$')]),
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='task_queue',
            field=models.ForeignKey(help_text='The queue this instance runs on', on_delete=django.db.models.deletion.PROTECT, to='tasksapi.TaskQueue'),
        ),
        migrations.AlterField(
            model_name='taskqueue',
            name='active',
            field=models.BooleanField(default=True, help_text='A boolean showing the status of the queue. As of now, this needs to be toggled manually. Defaults to True.'),
        ),
        migrations.AlterField(
            model_name='taskqueue',
            name='private',
            field=models.BooleanField(default=False, help_text='A boolean specifying whether other users besides the queue creator can use the queue. Defaults to False.'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='directories_to_bind',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='A JSON dictionary where the keys are directories on the worker\'s machine and the corresponding values are directories in the container to bind the keys to. E.g., {"home/worker/images/": "/images/"}. Make sure the directories in the container are created and ready to bind. Defaults to {}.'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='environment_variables',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text="A JSON array of environment variables to consume from the Celery worker's environment. Defaults to []."),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='logs_path',
            field=models.CharField(blank=True, default='/logs/', help_text='The path of the logs directory inside of the container. Specify null if no logs directory. Defaults to "/logs/".', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='required_arguments',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='A JSON array of required argument names. Defaults to [].'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='required_arguments_default_values',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='A JSON dictionary of default values for required arguments, where the keys are the argument names and the values are their corresponding default values. Defaults to {}.'),
        ),
    ]
