# Generated by Django 2.0.7 on 2018-08-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksapi', '0008_auto_20180727_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktype',
            name='directories_to_bind',
        ),
        migrations.AddField(
            model_name='tasktype',
            name='results_path',
            field=models.CharField(blank=True, default=None, help_text='The path of the results (or "outputs") directory inside of the container. Specify null if no results directory. Defaults to null.', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='logs_path',
            field=models.CharField(blank=True, default=None, help_text='The path of the logs directory inside of the container. Specify null if no logs directory. Defaults to null.', max_length=400, null=True),
        ),
    ]
