# Generated by Django 2.0.7 on 2018-08-09 16:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasksapi', '0009_auto_20180808_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktype',
            name='environment_variables',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text="A JSON array of environment variables to consume from the Celery worker's environment. Defaults to []. Note that all task instances have their job UUID available in the environment variable JOB_UUID."),
        ),
    ]
